name: Continuous Integration
on:
  push:
    branches:
    - master
    paths:
    - 'actions/**'
    - 'Dockerfile'

jobs:
  docker:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: oakela

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry 🔢
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin || true

      - name: Pull latest${{ matrix.image.tag_ext }} Docker image for caching
        run: docker pull rasa/helpdesk-assistant:latest || true

      - name: Set Build ID from run ID and number
        run: echo ::set-env name=BUILD_NUMBER::$GITHUB_RUN_NUMBER-$GITHUB_RUN_ID

      - name: Build latest${{ matrix.image.tag_ext }} Docker image
        run: docker build . --tag rasa/helpdesk-assistant:latest --tag rasa/helpdesk-assistant:run$BUILD_NUMBER --cache-from rasa/helpdesk-assistant:latest

      - name: Push image with latest tag 📦
        run: docker push rasa/helpdesk-assistant